export const templateList = [
  { fill: '#FFF', stroke: '#000000', textBackgroundColor: undefined },
  { fill: '#000000', stroke: '#ffffff', textBackgroundColor: undefined },
  { fill: '#FFDE02', stroke: '#000000', textBackgroundColor: undefined },
  { fill: '#FFF', stroke: '#F57165', textBackgroundColor: undefined },
  { fill: '#B7DCF6', stroke: '#000000', textBackgroundColor: undefined },
  { fill: '#FFD9E8', stroke: '#FF619D', textBackgroundColor: undefined },
  { fill: '#C0F1F5', stroke: '#1B81E7', textBackgroundColor: undefined },
  { fill: '#DCE57E', stroke: '#2B6323', textBackgroundColor: undefined },
  { fill: '#C1E8BF', stroke: '#027B88', textBackgroundColor: undefined },
  { fill: '#FFF', stroke: '#FF2570', textBackgroundColor: undefined },
  { fill: '#AB4A37', stroke: '#ffffff', textBackgroundColor: undefined },
  { fill: '#F9F3C4', stroke: '#4A4238', textBackgroundColor: undefined },
  { fill: '#FFD9C6', stroke: '#A74F59', textBackgroundColor: undefined },
  { fill: '#69F0AE', stroke: '#000000', textBackgroundColor: undefined },
  { fill: '#FFF', stroke: '#00A16C', textBackgroundColor: undefined },
  { fill: '#0A0A15', stroke: undefined, textBackgroundColor: '#fff' },
  { fill: '#FFF', stroke: undefined, textBackgroundColor: '#000000' },
  { fill: '#FFF', stroke: undefined, textBackgroundColor: '#EB6969' },
  { fill: '#000', stroke: undefined, textBackgroundColor: '#FFDE02' },
  { fill: '#FFF', stroke: undefined, textBackgroundColor: '#00A16C' },
  { fill: '#FFF', stroke: undefined, textBackgroundColor: '#2994D8' },
]
